[package]
name = "carbon_scheduler"
version = "0.0.0"
edition = "2021"
author = "GorillaDevs Inc."

[dependencies]
futures = "0.3.25"
parking_lot = "0.12.1"
rayon = "1.9.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-test = "0.2.4"
